title: gawk
description: GNU Awk 5.4.1 的静态构建 (含 bundled .so + RPATH 跨平台便携)
repo: gawk
baseurl: ""
url: "https://gawk.ljh.sh"
theme: ~

permalink: pretty
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
